import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import semver from "semver";
import {
  authDir,
  coreVersion,
  defaultCoreRange,
  generatedNodeTypesRange,
  generatedTsxRange,
  generatedTypeScriptRange,
  remoteMcpUrl,
} from "../../shared/constants.js";
import type { TemplateInput } from "../../shared/types.js";

export function renderTemplate(input: TemplateInput): { files: Record<string, string> } {
  const coreRange = resolveCoreRange(input.coreVersionRange);
  return {
    files: {
      "README.md": renderReadme(input, coreRange),
      "package.json": JSON.stringify(
        {
          name: input.projectName,
          version: "0.1.0",
          private: true,
          type: "module",
          scripts: {
            dev: "tsx src/index.ts",
            build: "tsc -p tsconfig.json",
            start: "node dist/index.js",
          },
          dependencies: {
            "@fentaris/core": coreRange,
            tsx: generatedTsxRange,
          },
          devDependencies: {
            "@types/node": generatedNodeTypesRange,
            typescript: generatedTypeScriptRange,
          },
        },
        null,
        2,
      ),
      "tsconfig.json": JSON.stringify(
        {
          compilerOptions: {
            target: "ES2022",
            module: "NodeNext",
            moduleResolution: "NodeNext",
            strict: true,
            esModuleInterop: true,
            skipLibCheck: true,
            outDir: "dist",
            rootDir: "src",
          },
          include: ["src"],
        },
        null,
        2,
      ),
      "fentaris.json": JSON.stringify(
        {
          name: input.projectName,
          packageManager: input.packageManager,
          entrypoint: "src/index.ts",
          port: input.port,
          host: "127.0.0.1",
          path: input.proxyPath,
          authDir,
        },
        null,
        2,
      ),
      ".gitignore": [
        "node_modules/",
        "dist/",
        ".env",
        ".env.*",
        ".fentaris/*",
        "!.fentaris/secrets.manifest.json",
        ".fentaris/build/",
        "*.log",
        "",
      ].join("\n"),
      ".fentaris/secrets.manifest.json": JSON.stringify({ version: 1, references: [] }, null, 2),
      "src/index.ts": renderEntrypoint(),
    },
  };
}

export function renderEntrypoint(): string {
  return `import { Policy, fentaris, streamableHttp } from "@fentaris/core";

const app = fentaris({
  // Development-only: replace this with an explicit policy before sharing the proxy.
  policy: Policy.allowAll(),
});

app.mcp("specification", {
  transport: streamableHttp({
    url: "${remoteMcpUrl}",
  }),
});

app.mcp("specification").on("tool:success", ({ ctx, durationMs }) => {
  console.log(\`specification -> \${ctx.tool?.name ?? ctx.operation} (\${durationMs}ms)\`);
});

await app.start();
`;
}

export async function writeTemplate(targetDir: string, files: Record<string, string>): Promise<void> {
  for (const [relativePath, contents] of Object.entries(files)) {
    const filePath = path.join(targetDir, relativePath);
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, contents);
  }
}

function renderReadme(input: TemplateInput, coreRange: string): string {
  return `# ${input.projectName}

This project was generated by the Fentaris CLI. It starts a local MCP proxy with a remote HTTP MCP server mounted as \`specification\`.

## Quick start

\`\`\`sh
${input.packageManager} install
${input.packageManager} dev
\`\`\`

\`fentaris dev\` starts the project. The proxy listens on \`http://127.0.0.1:${input.port}${input.proxyPath}\` by default.

The generated \`Policy.allowAll()\` policy is for local development only. Replace it with an explicit allow-list policy before sharing or exposing the proxy.

The generated project pins \`@fentaris/core\` to \`${coreRange}\` (currently \`^${coreVersion}\` by default). Run \`${input.packageManager} outdated @fentaris/core\` to check for compatible updates, then \`${input.packageManager} update @fentaris/core\` to install them.

## Project files

- \`src/index.ts\` configures the upstream MCP server.
- \`fentaris.json\` configures the project entrypoint, port, path, and CLI defaults.
- \`.fentaris/secrets.manifest.json\` lists required credential references (schema only, safe to commit).

## Useful commands

\`\`\`sh
fentaris doctor
fentaris check --offline
fentaris build
\`\`\`
`;
}

function resolveCoreRange(value: string | undefined): string {
  const candidate = (value ?? defaultCoreRange).trim();
  if (!candidate) {
    throw new Error("@fentaris/core version range is required.");
  }

  if (candidate === "latest" || candidate === "next" || candidate === "beta" || candidate === "canary") {
    return candidate;
  }

  if (candidate.startsWith("workspace:") || candidate.startsWith("file:") || candidate.startsWith("link:") || candidate.startsWith("portal:")) {
    return candidate;
  }

  if (candidate.startsWith("npm:") || candidate.startsWith("git:") || candidate.startsWith("github:") || candidate.startsWith("http:") || candidate.startsWith("https:")) {
    return candidate;
  }

  if (candidate.startsWith("git+ssh:") || candidate.startsWith("git+http:") || candidate.startsWith("git+https:")) {
    return candidate;
  }

  if (isValidSemverRange(candidate)) {
    return candidate;
  }

  throw new Error(
    `Invalid --core-version value '${candidate}'. Use a semver range (e.g. ^2.0.0, ~2.0.0, 2.0.0), a dist tag (latest, next), or a workspace/file reference.`,
  );
}

function isValidSemverRange(value: string): boolean {
  return semver.validRange(value) !== null;
}
