import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { authDir, remoteMcpUrl } from "../../shared/constants.js";
import type { TemplateInput } from "../../shared/types.js";

export function renderTemplate(input: TemplateInput): { files: Record<string, string> } {
  return {
    files: {
      "README.md": renderReadme(input),
      "package.json": JSON.stringify(
        {
          name: input.projectName,
          version: "0.1.0",
          private: true,
          type: "module",
          scripts: {
            dev: "tsx src/index.ts",
            build: "tsc -p tsconfig.json",
            start: "node dist/index.js",
          },
          dependencies: {
            "@fentaris/core": "latest",
            tsx: "latest",
          },
          devDependencies: {
            "@types/node": "latest",
            typescript: "latest",
          },
        },
        null,
        2,
      ),
      "tsconfig.json": JSON.stringify(
        {
          compilerOptions: {
            target: "ES2022",
            module: "NodeNext",
            moduleResolution: "NodeNext",
            strict: true,
            esModuleInterop: true,
            skipLibCheck: true,
            outDir: "dist",
            rootDir: "src",
          },
          include: ["src"],
        },
        null,
        2,
      ),
      "fentaris.json": JSON.stringify(
        {
          name: input.projectName,
          packageManager: input.packageManager,
          entrypoint: "src/index.ts",
          port: input.port,
          path: input.proxyPath,
          authDir,
        },
        null,
        2,
      ),
      ".gitignore": [
        "node_modules/",
        "dist/",
        ".env",
        ".env.*",
        ".fentaris/",
        "!.fentaris/secrets.manifest.json",
        ".fentaris/build/",
        "*.log",
        "",
      ].join("\n"),
      ".fentaris/secrets.manifest.json": JSON.stringify({ version: 1, references: [] }, null, 2),
      "src/index.ts": renderEntrypoint(input),
    },
  };
}

export function renderEntrypoint(input: TemplateInput): string {
  return `import { fentaris, streamableHttp } from "@fentaris/core";

const app = fentaris({
  user: { id: "demo" },
});

app.mcp("specification", {
  transport: streamableHttp({
    url: "${remoteMcpUrl}",
  }),
});

app.mcp("specification").on("tool:success", ({ ctx, durationMs }) => {
  console.log(\`specification -> \${ctx.tool?.name ?? ctx.operation} (\${durationMs}ms)\`);
});

await app.start();
`;
}

export async function writeTemplate(targetDir: string, files: Record<string, string>): Promise<void> {
  for (const [relativePath, contents] of Object.entries(files)) {
    const filePath = path.join(targetDir, relativePath);
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, contents);
  }
}

function renderReadme(input: TemplateInput): string {
  return `# ${input.projectName}

This project was generated by the Fentaris CLI. It starts a local MCP proxy with:

- A remote HTTP MCP server mounted as \`specification\`
- One local demo user and no authentication or policy configuration

## Quick start

\`\`\`sh
${input.packageManager} install
${input.packageManager} dev
\`\`\`

\`fentaris dev\` starts the project. The proxy listens on \`http://localhost:${input.port}${input.proxyPath}\` by default.

## Project files

- \`src/index.ts\` configures the app user and upstream MCP server.
- \`fentaris.json\` configures the project entrypoint, port, path, and CLI runtime defaults.
- \`.fentaris/secrets.manifest.json\` lists required credential references (schema only, safe to commit).

## Secrets workflow

\`\`\`sh
fentaris secrets set github.token
fentaris secrets list
fentaris secrets manifest
fentaris doctor
\`\`\`

## Useful commands

\`\`\`sh
fentaris check --offline
fentaris build
\`\`\`
`;
}
